---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  labels:
    custom: gitops-operator-policy
  name: placement-boot-projects-dev
  namespace: open-cluster-management-global-set
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - {key: boot-projects-dev, operator: In, values: ["true"]}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  labels:
    custom: gitops-operator-policy
  name: placement-boot-projects-test
  namespace: open-cluster-management-global-set
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - {key: boot-projects-test, operator: In, values: ["true"]}
